notify-team condition check

diff --git a/.github/workflows/notify-teams.yml b/.github/workflows/notify-teams.yml
--- a/.github/workflows/notify-teams.yml
+++ b/.github/workflows/notify-teams.yml
@@ -9,44 +9,40 @@ env:
   MS_TEAMS_WEBHOOK_URL: https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41
 
 jobs:
-
-  java-build:
+    build:
     runs-on: ubuntu-latest
- 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
- 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
-        with:
-          java-version: '11'
- 
-      - name: Debug file structure (for troubleshooting)
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Run Build Command
         run: |
-          echo "Printing the file structure..."
-          pwd  # Print working directory
-          ls -la  # List files to confirm HelloWorld.java exists
-     
-      - name: Compile Java program
-        run: |
-          echo "Compiling the Java program..."
-          javac HelloWorld.java
- 
-      - name: Run Java program
-        run: |
-          echo "Running the Java program..."
-          java HelloWorld
- 
-      - name: java
-        run: echo "Hello ..."
+          echo "Building the project..."
+          exit 1  
+      # Simulated failure
 
   send_notification:
-    needs: java-build
     runs-on: ubuntu-latest
     steps:
-      - name: Send Teams Notification
+    needs: build
+
+    #success
+      - name: Send Success Notification
+        if: success()
         run: |
+          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+          MESSAGE="Build succeeded on branch $BRANCH_NAME! Commit: $COMMIT_MESSAGE !!"
+
           curl -X POST -H "Content-Type: application/json" \
             -d '{"text": "repo Link: ${{ github.repository }}"}' \
+            $MS_TEAMS_WEBHOOK_URL
+            
+    #failure
+      - name: Send Failure Notification
+        if: failure()
+        run: |
+          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+          MESSAGE="Build failed on branch $BRANCH_NAME! Commit: $COMMIT_MESSAGE. Please check the logs."
+
+          curl -X POST -H "Content-Type: application/json" \
+            -d '{"text": "$MESSAGE"}' \
             $MS_TEAMS_WEBHOOK_URL
